Squash a -Wformat-pedantic warning that was added in recent clang
src/vmm/io/vhpet.c:294:60: error: format specifies type 'void *' but the argument has type 'struct vhpet *' [-Werror,-Wformat-pedantic]
                xhyve_abort("vhpet(%p) callout with counter disabled\n", vhpet);
                                   ~~                                    ^~~~~
In file included from src/vmm/io/vhpet.c:35:
include/xhyve/support/misc.h:22:19: note: expanded from macro 'xhyve_abort'
                fprintf(stderr, __VA_ARGS__); \
                                ^
1 error generated.

Signed-off-by: Jeremy Huddleston Sequoia <jeremyhu@apple.com>